[project]
name = "bibpay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "django>=5.2.8",
    "djangorestframework>=3.16.1",
    "python-decouple>=3.8",
    "requests>=2.32.5",
]
